### ISSUE TITLE
想请教一下如何控制点击表格时每一行样式的改变

### ISSUE THREAD

**Issue by yingjiahuan** [Rain120/Web-Study#1]
$('#meetingRooms tbody').on('click', 'tr', function () {
            if ( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
            }else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        });
这段代码中 selected 类是在哪里写的？

**Comment by Rain120** [comment]
srr, 我没有及时查看这个repo
eg:
```html
<tr class="t-row">
    <td class="selected"></td>
</tr>
```

```css
.t-row {}
.selected {}
```
